# Utiliza una imagen base de Node.js para la fase de compilación
FROM node:18 AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación Angular
COPY . .

# Construye la aplicación Angular
RUN npm run build --prod

# Utiliza una imagen base de NGINX para servir la aplicación
FROM nginx:alpine

# Copia los archivos construidos desde la imagen de Node.js
COPY --from=build /app/dist/proyectosof2 /usr/share/nginx/html

# Expone el puerto en el que correrá la aplicación
EXPOSE 4200

# Comando para ejecutar NGINX
CMD ["nginx", "-g", "daemon off;"]
